### ISSUE TITLE
Add cross-compilation

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hermes#8]
## Feature
Add cross-compilation

**Comment by wajda** [comment]
Why do you need a cross compilation on this? Is it intended to be linked with another Scala module?

**Comment by Zejnilovic** [comment]
> Why do you need a cross compilation on this? Is it intended to be linked with another Scala module?

It was made so it can be. It is not intended for now for any of the AbsaOSS projects as far as I know. But it is intentionally allowed and should be supported. 

And this is going to be like 5 lines of code, so why not in the end.

**Comment by wajda** [comment]
Not sure I get it. You are going to compile it (and I presume even deploy to sonatype) N times just because you can?

**Comment by Zejnilovic** [comment]
I am going to make sure it can be cross compiled and add the option just because I can, yes.

I don't know about the sonatype. Maybe. We'll see.
